#! /bin/sh

# Usage: patch @VARIABLE@ value

varname="$1"
varvalue="$2"

case `uname` in
    MINGW*)
        # Convert the first letter drive to DOS style (naive).
        # This is necessary because OCaml uses DOS paths even if
        # run under MSYS.
        varvalue="$(echo "$varvalue" | sed -e 's;^/\([a-z]\)/;\1:/;g')"
        ;;
esac

varvalue="$(echo "$varvalue" | sed -e 's;\\;\\\\\\\\;g;s/;/\\;/g')"

sed -e 's;'"$varname"';'"$varvalue"';g'
# e.g. c:\\\\file is parsed by sed as c:\\file which is correct for the
# ocaml string
