name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os.windows_environment == '' && matrix.os.name || format('windows-latest/{0}', matrix.os.windows_environment) }} - OCaml ${{ matrix.ocaml-version }}

    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest, LTS, and newest supported
      # OCaml versions.
      matrix:
        os:
          - name: macos-latest
          - name: ubuntu-latest
          - name: windows-latest
            windows_environment: cygwin
          - name: windows-latest
            windows_environment: msys2
        ocaml-version:
          - "4.14"
          - "5.4"
          - "5.5"
        include:
          - os:
              name: ubuntu-latest
            ocaml-version: "3.08"

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          windows-environment: ${{ matrix.os.windows_environment == '' && 'cygwin' || matrix.os.windows_environment }}
          opam-repositories: |
            default: git+https://github.com/ocaml/opam-repository.git
            archive: git+https://github.com/ocaml/opam-repository-archive.git

      - name: Build with make
        run: |
          opam exec -- ${{ runner.os == 'Windows' && 'sh ' || '' }}./configure -sitelib .
          echo ------------
          grep "[\\\\/]" Makefile.config
          echo ------------
          opam exec -- make all opt

      - name: Build and install with opam
        id: opam
        env:
          SOURCE_DATE_EPOCH: 0
          OCAMLPARAM: ${{ runner.os == 'macOS' && '|_|cclib=-Wl,-S' || '' }}
        run: |
          opam pin add ocamlfind .
          sh -c 'echo "relocatable=$(test -n "$(opam list --installed --short compiler-cloning.enabled)" && echo "true" || echo "false")" >> "$GITHUB_OUTPUT"'

      - name: Test the ocamlfind binary
        env:
          OPT: ${{ matrix.ocaml-version == '3.08' && '-version' || '-config' }}
        run: |
          opam exec -- ocamlfind list
          echo ------------
          opam exec -- ocamlfind printconf
          echo ------------
          opam exec -- ocamlfind opt ${{ env.OPT }}
          echo ------------
          opam exec -- ocamlfind printconf conf | tr -d '\r' | tr '\\' '/' | xargs cat

      - name: Test the toplevel plugin
        run: opam exec -- ocaml .github/workflows/toplist.ml

      - name: Create second switch (relocatable)
        if: steps.opam.outputs.relocatable == 'true'
        shell: bash
        env:
          SOURCE_DATE_EPOCH: 0
          OCAMLPARAM: ${{ runner.os == 'macOS' && '|_|cclib=-Wl,-S' || '' }}
        run: |
          opam switch create second --no-switch $(opam list --color=never --columns=package --short --installed ocaml | tr -d '\r')
          opam pin add --switch=second ocamlfind .

      - name: Check ocamlfind is relocatable
        if: steps.opam.outputs.relocatable == 'true'
        shell: bash
        run: |
          first="$(opam var bin | tr -d '\r')/ocamlfind${{ runner.os == 'Windows' && '.exe' || '' }}"
          second="$(opam var --switch=second bin | tr -d '\r')/ocamlfind${{ runner.os == 'Windows' && '.exe' || '' }}"
          sha1sum "$first" "$second"
          if ! cmp -s "$first" "$second"; then
            if command -v xxd > /dev/null; then
              diff <(xxd "$first") <(xxd "$second") || true
            else
              diff <(od -A x -t x1 -v "$first") <(od -A x -t x1 -v "$second") || true
            fi
            exit 1
          fi
