name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - OCaml ${{ matrix.ocaml-version }}

    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest, LTS, and newest supported
      # OCaml versions.
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - "4.14"
          - "5.4"
        include:
          - os: ubuntu-latest
            ocaml-version: "3.08"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Build with make
        run: |
          opam exec -- ${{ runner.os == 'Windows' && 'sh ' || '' }}./configure
          opam exec -- make all opt

      - name: Build and install with opam
        run: opam pin add ocamlfind .

      - name: Test the ocamlfind binary
        env:
          OPT: ${{ matrix.ocaml-version == '3.08' && '-version' || '-config' }}
        run: |
          opam exec -- ocamlfind list
          opam exec -- ocamlfind printconf
          opam exec -- ocamlfind opt ${{ env.OPT }}

      - name: Test the toplevel plugin
        run: opam exec -- ocaml .github/workflows/toplist.ml
