name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os.windows_environment == '' && matrix.os.name || format('windows-latest/{0}', matrix.os.windows_environment) }} - OCaml ${{ matrix.ocaml-version }}

    strategy:
      fail-fast: false
      # Test Linux, macOS and Windows with the oldest, LTS, and newest supported
      # OCaml versions.
      matrix:
        os:
          - name: macos-latest
          - name: ubuntu-latest
          - name: windows-latest
            windows_environment: cygwin
          - name: windows-latest
            windows_environment: msys2
        ocaml-version:
          - "4.14"
          - "5.4"
          - "5.5"
        include:
          - os:
              name: ubuntu-latest
            ocaml-version: "3.08"

    runs-on: ${{ matrix.os.name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set-up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          windows-environment: ${{ matrix.os.windows_environment == '' && 'cygwin' || matrix.os.windows_environment }}
          opam-repositories: |
            default: git+https://github.com/ocaml/opam-repository.git
            archive: git+https://github.com/ocaml/opam-repository-archive.git

      - name: Build with make
        run: |
          opam exec -- ${{ runner.os == 'Windows' && 'sh ' || '' }}./configure -sitelib .
          echo ------------
          grep "[\\\\/]" Makefile.config
          echo ------------
          opam exec -- make all opt

      - name: Build and install with opam
        run: opam pin add ocamlfind .

      - name: Test the ocamlfind binary
        env:
          OPT: ${{ matrix.ocaml-version == '3.08' && '-version' || '-config' }}
        run: |
          opam exec -- ocamlfind list
          echo ------------
          opam exec -- ocamlfind printconf
          echo ------------
          opam exec -- ocamlfind opt ${{ env.OPT }}
          echo ------------
          opam exec -- ocamlfind printconf conf | tr -d '\r' | tr '\\' '/' | xargs cat

      - name: Test the toplevel plugin
        run: opam exec -- ocaml .github/workflows/toplist.ml
